version: 2
jobs:
  build:
    docker:
      - image: linuxbrew/brew
        user: linuxbrew
    environment:
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
    steps:
      - run:
          name: Install minimal python for libxcb build
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends python2.7-minimal
      - run:
          name: Set up Git
          command: |
            git config --global user.name LinuxbrewTestBot
            git config --global user.email testbot@linuxbrew.sh
      - run:
          name: Remember date for caching purposes
          command: date +%F > date
      - restore_cache:
          keys:
            - linuxbrew-daily-cache-{{ checksum "date" }}
            - linuxbrew-daily-cache
      - run:
          name: Fetch Homebrew/brew
          working_directory: /home/linuxbrew/.linuxbrew/Homebrew
          command: git fetch origin --tags
      - save_cache:
          key: linuxbrew-daily-cache-{{ checksum "date" }}
          paths:
            - /home/linuxbrew/.linuxbrew/Homebrew/.git
      - restore_cache:
          keys:
            - homebrew-core-daily-cache-{{ checksum "date" }}
            - homebrew-core-daily-cache
      - run:
          name: Update & reset Homebrew
          command: brew update-reset
      - save_cache:
          key: homebrew-core-daily-cache-{{ checksum "date" }}
          paths:
            - /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
      - restore_cache:
          keys:
            - linuxbrew-xorg-daily-cache-{{ checksum "date" }}
            - linuxbrew-xorg-daily-cache
      - run:
          name: Tap Linuxbrew/xorg
          command: brew tap linuxbrew/xorg
      - save_cache:
          key: linuxbrew-xorg-daily-cache-{{ checksum "date" }}
          paths:
            - /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg
      - run:
          name: Configure Linuxbrew/xorg tap
          working_directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg
          command: |
            git pull origin master
            if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
                git fetch origin pull/$CIRCLE_PR_NUMBER/head
            fi
            git reset --hard $CIRCLE_SHA1
      - run:
          name: Install patchelf
          command: brew install patchelf
      - run:
          name: Main test (test-bot)
          working_directory: /tmp/bottles
          no_output_timeout: 30m
          command: |
            brew test-bot --tap=linuxbrew/xorg \
                   --bintray-org=linuxbrew \
                   --git-email=testbot@linuxbrew.sh \
                   --git-name=LinuxbrewTestBot \
                   --skip-recursive-dependents

      - store_artifacts:
          path: /tmp/bottles
          destination: bottles
      - store_test_results:
          path: /tmp/bottles
notify:
  webhooks:
    - url: https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload
