version: 2
jobs:
  build:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
      HOMEBREW_VERBOSE_USING_DOTS: 1
    steps:
      - run:
          name: Install minimal python for libxcb build
          command: |
            sudo apt-get update
            sudo apt-get install --yes --force-yes python2.7-minimal
      - run:
          name: Set up Git
          command: |
            git config --global user.name LinuxbrewTestBot
            git config --global user.email testbot@linuxbrew.sh
      - run:
          name: Update Linuxbrew
          command: brew update
      - run:
          name: Set up linuxbrew/xorg tap
          working_directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew
          command: |
            git clone https://github.com/Linuxbrew/$CIRCLE_PROJECT_REPONAME
            cd $CIRCLE_PROJECT_REPONAME
            if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
                git fetch origin pull/$CIRCLE_PR_NUMBER/head
            fi
            git reset --hard $CIRCLE_SHA1
      - run:
          name: Prepare for the main test
          command: brew install patchelf
      - run:
          name: Main test
          working_directory: /tmp/bottles
          no_output_timeout: 30m
          command: brew test-bot --tap=linuxbrew/xorg --bintray-org=linuxbrew --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
      - store_artifacts:
          path: /tmp/bottles
          destination: bottles
      - store_test_results:
          path: /tmp/bottles
notify:
  webhooks:
    - url: https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload
